version: '3.7'

services:
  nginx:
    build:
      context: .
      target: nginx
    volumes:
      - ./laravel/public:/var/www/html/public:ro
    ports:
      - 8001:80
    environment:
      PHP_HOST: app

  app:
    build:
      context: .
      target: app
    env_file:
      - ./laravel/.env.example
    volumes:
      - ./laravel:/var/www/html:cached

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/db/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'app'
    ports:
      - 3306